# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: siqili's Blog
brief-intro: 要多想
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zhuzm.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: N/A
facebook_username: N/A
github_username: siqili1230
email: siqili1230@gmail.com
weibo_username: N/A
zhihu_username: N/A
linkedIn_username: 
dribbble_username:

description_footer: 好的

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: 
disqus_shortname: 
gitment_id: b2e42628cfab01b65ef0
gitment_secret: db08408d876fbddc402af845b78e6f1625f72e93

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 
google_analytics_id: UA-119118847-1 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 10
